/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `/import-statement`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/loans` | `/loans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/you` | `/you`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/cash-setup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/csv-import`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/income-rhythm`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/loans-emi`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/user-type`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-entry`; params?: Router.UnknownOutputParams; } | { pathname: `/import-statement`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/loans` | `/loans`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/you` | `/you`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/cash-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/csv-import`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/income-rhythm`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/loans-emi`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/user-type`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-entry${`?${string}` | `#${string}` | ''}` | `/import-statement${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/loans${`?${string}` | `#${string}` | ''}` | `/loans${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/you${`?${string}` | `#${string}` | ''}` | `/you${`?${string}` | `#${string}` | ''}` | `/onboarding/cash-setup${`?${string}` | `#${string}` | ''}` | `/onboarding/complete${`?${string}` | `#${string}` | ''}` | `/onboarding/csv-import${`?${string}` | `#${string}` | ''}` | `/onboarding/income-rhythm${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/loans-emi${`?${string}` | `#${string}` | ''}` | `/onboarding/user-type${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `/import-statement`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/loans` | `/loans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/you` | `/you`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/cash-setup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/csv-import`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/income-rhythm`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/loans-emi`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/user-type`; params?: Router.UnknownInputParams; };
    }
  }
}
